-- MySQL Script generated by MySQL Workbench
-- Mon Oct 31 00:01:15 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mi portafolio
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mi portafolio
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mi portafolio` DEFAULT CHARACTER SET utf8 ;
USE `mi portafolio` ;

-- -----------------------------------------------------
-- Table `mi portafolio`.`Persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mi portafolio`.`Persona` (
  `id` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `telefono` VARCHAR(20) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `sobre_Mi` LONGTEXT NULL,
  `url_Foto` VARCHAR(100) NULL,
  `url_Banner` VARCHAR(100) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mi portafolio`.`Experiencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mi portafolio`.`Experiencia` (
  `id` INT NOT NULL,
  `url_Imagen` VARCHAR(100) NULL,
  `nombre` VARCHAR(45) NULL,
  `fecha_Inicio` DATE NULL,
  `fecha_Fin` DATE NULL,
  `puesto` VARCHAR(45) NULL,
  `descripcion` LONGTEXT NULL,
  `Persona_id` INT NOT NULL,
  PRIMARY KEY (`id`, `Persona_id`),
  INDEX `fk_Experiencia_Persona1_idx` (`Persona_id` ASC) VISIBLE,
  CONSTRAINT `fk_Experiencia_Persona1`
    FOREIGN KEY (`Persona_id`)
    REFERENCES `mi portafolio`.`Persona` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mi portafolio`.`Redes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mi portafolio`.`Redes` (
  `id` INT NOT NULL,
  `url_Imagen` VARCHAR(100) NULL,
  `url_direccion` VARCHAR(45) NULL,
  `Persona_id` INT NOT NULL,
  PRIMARY KEY (`id`, `Persona_id`),
  INDEX `fk_Redes_Persona_idx` (`Persona_id` ASC) VISIBLE,
  CONSTRAINT `fk_Redes_Persona`
    FOREIGN KEY (`Persona_id`)
    REFERENCES `mi portafolio`.`Persona` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mi portafolio`.`Habilidades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mi portafolio`.`Habilidades` (
  `id` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `porcentaje` VARCHAR(45) NULL,
  `url_Imagen` VARCHAR(45) NULL,
  `Persona_id` INT NOT NULL,
  PRIMARY KEY (`id`, `Persona_id`),
  INDEX `fk_Habilidades_Persona1_idx` (`Persona_id` ASC) VISIBLE,
  CONSTRAINT `fk_Habilidades_Persona1`
    FOREIGN KEY (`Persona_id`)
    REFERENCES `mi portafolio`.`Persona` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mi portafolio`.`Estudios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mi portafolio`.`Estudios` (
  `id` INT NOT NULL,
  `url_imagen` VARCHAR(100) NULL,
  `nombre_Escuela` VARCHAR(45) NULL,
  `Titulo` VARCHAR(45) NULL,
  `estado_Estudio` VARCHAR(45) NULL,
  `fecha_Inicio` DATE NULL,
  `fecha_Fin` DATE NULL,
  `Persona_id` INT NOT NULL,
  PRIMARY KEY (`id`, `Persona_id`),
  INDEX `fk_Estudios_Persona1_idx` (`Persona_id` ASC) VISIBLE,
  CONSTRAINT `fk_Estudios_Persona1`
    FOREIGN KEY (`Persona_id`)
    REFERENCES `mi portafolio`.`Persona` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mi portafolio`.`Proyecto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mi portafolio`.`Proyecto` (
  `id` INT NOT NULL,
  `url_Imagen` VARCHAR(100) NULL,
  `nombre_Empresa` VARCHAR(45) NULL,
  `fecha_Realizacion` DATE NULL,
  `descripcion` LONGTEXT NULL,
  `Persona_id` INT NOT NULL,
  PRIMARY KEY (`id`, `Persona_id`),
  INDEX `fk_Proyecto_Persona1_idx` (`Persona_id` ASC) VISIBLE,
  CONSTRAINT `fk_Proyecto_Persona1`
    FOREIGN KEY (`Persona_id`)
    REFERENCES `mi portafolio`.`Persona` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
